import type { MenuGrupo, MenuItem } from './menu-types';

export const MENU_GRUPOS: MenuGrupo[] = [
  { id: 'produtividade', rotulo: 'Produtividade', icone: 'fa-solid fa-chart-line' },
  { id: 'producao', rotulo: 'Produção', icone: 'fa-solid fa-industry' },
  { id: 'estoque', rotulo: 'Estoque', icone: 'fa-solid fa-boxes-stacked' },
  { id: 'financeiro', rotulo: 'Financeiro', icone: 'fa-solid fa-building-columns' },
  { id: 'ferramentas', rotulo: 'Ferramentas', icone: 'fa-solid fa-screwdriver-wrench' },
  { id: 'organizacao', rotulo: 'Pessoas e gestão', icone: 'fa-solid fa-sitemap' },
];

export const MENU_ITENS: MenuItem[] = [
  {
    id: 'gerenciar-producao',
    rotulo: 'Gerenciar Produção',
    href: '/admin/gerenciar-producao.html',
    icone: 'fa-solid fa-list-check',
    grupo: 'produtividade',
    permissao: 'acesso-gerenciar-producao',
    modulo: 'gerenciar-producao',
  },
  {
    id: 'producao-geral',
    rotulo: 'Produção Geral',
    href: '/admin/producao-geral.html',
    icone: 'fa-solid fa-gauge-high',
    grupo: 'produtividade',
    permissao: 'acesso-producao-geral',
    modulo: 'producao-geral',
  },
  {
    id: 'cadastrar-produto',
    rotulo: 'Cadastrar Produto',
    href: '/admin/cadastrar-produto.html',
    icone: 'fa-solid fa-shirt',
    grupo: 'producao',
    permissao: 'acesso-cadastrar-produto',
    modulo: 'produtos',
  },
  {
    id: 'ordens-producao',
    rotulo: 'Ordens de Produção',
    href: '/admin/ordens-de-producao.html',
    icone: 'fa-solid fa-clipboard-list',
    grupo: 'producao',
    permissao: 'acesso-ordens-de-producao',
    modulo: 'ordens-producao',
  },
  {
    id: 'arremates',
    rotulo: 'Arremates',
    href: '/admin/arremates.html',
    icone: 'fa-solid fa-scissors',
    grupo: 'producao',
    permissao: 'acesso-ordens-de-arremates',
    modulo: 'arremates',
  },
  {
    id: 'embalagem',
    rotulo: 'Embalagem de Produtos',
    href: '/admin/embalagem-de-produtos.html',
    icone: 'fa-solid fa-box-open',
    grupo: 'producao',
    permissao: 'acesso-embalagem-de-produtos',
    modulo: 'embalagem',
  },
  {
    id: 'estoque',
    rotulo: 'Controle de Estoque',
    href: '/admin/estoque.html',
    icone: 'fa-solid fa-boxes-stacked',
    grupo: 'estoque',
    permissao: 'acesso-estoque',
    modulo: 'estoque',
  },
  {
    id: 'financeiro',
    rotulo: 'Controle Financeiro',
    href: '/admin/financeiro.html',
    icone: 'fa-solid fa-wallet',
    grupo: 'financeiro',
    permissao: 'acesso-financeiro',
    modulo: 'financeiro',
  },
  {
    id: 'central-pagamentos',
    rotulo: 'Central de Pagamentos',
    href: '/admin/central-de-pagamentos.html',
    icone: 'fa-solid fa-cash-register',
    grupo: 'financeiro',
    permissao: 'acessar-central-pagamentos',
    modulo: 'central-pagamentos',
  },
  {
    id: 'incentivos',
    rotulo: 'Centro de Incentivos',
    href: '/admin/incentivos.html',
    icone: 'fa-solid fa-trophy',
    grupo: 'ferramentas',
    permissao: 'acesso-ponto-por-processo',
    modulo: 'incentivos',
  },
  {
    id: 'alertas',
    rotulo: 'Central de Alertas',
    href: '/admin/config-alertas.html',
    icone: 'fa-solid fa-bell',
    grupo: 'ferramentas',
    permissao: 'configurar-alertas',
    modulo: 'alertas',
  },
  {
    id: 'calendario',
    rotulo: 'Calendário da Empresa',
    href: '/admin/calendario.html',
    icone: 'fa-solid fa-calendar-days',
    grupo: 'ferramentas',
    modulo: 'calendario',
  },
  {
    id: 'gestao-organizacional',
    rotulo: 'Gestão Organizacional',
    href: '/admin/gestao-organizacional.html',
    icone: 'fa-solid fa-sitemap',
    grupo: 'organizacao',
    permissao: 'acesso-gestao-organizacional',
    modulo: 'gestao-organizacional',
    aliases: ['/admin/usuarios-cadastrados.html'],
  },
];

export const MENU_FAVORITOS_PADRAO = [
  'financeiro',
  'ordens-producao',
  'gestao-organizacional',
];

export function itemMenuEstaAtivo(item: MenuItem, pathname = window.location.pathname) {
  return item.href === pathname || Boolean(item.aliases?.includes(pathname));
}
